apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: master
  name: master-svc
spec:
  type: NodePort
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
    nodePort: 30022
  selector:
    run: master
status:
  loadBalancer: {}
